server {
    listen 80;
    server_name localhost;

    location = /favicon.ico { access_log off; log_not_found off; }

    # Static files location
    location /static/ {
        alias /path/to/your/HMS/staticfiles/;
    }

    # Media files location
    location /media/ {
        alias /path/to/your/HMS/media/;
    }

    # Proxy to Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/hms.sock;
    }
}
